@ChatbotAPI_HostAddress = http://localhost:5189

GET {{ChatbotAPI_HostAddress}}/api/chat/messages
Accept: application/json

###

POST {{ChatbotAPI_HostAddress}}/api/chat/messages
Content-Type: application/json

{
    "userMessage": "Hello!",
    "botResponse": "Hi there!"
}

###

PUT {{ChatbotAPI_HostAddress}}/api/chat/messages/3
Content-Type: application/json

{
    "id": 3,
    "botResponse": "Response"
}

###

PUT {{ChatbotAPI_HostAddress}}/api/chat/messages/1/rating
Content-Type: application/json

"1"

###